# Generated by Django 4.2.19 on 2025-02-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meal_name", models.CharField(max_length=255)),
                ("meal_type", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255, null=True)),
                ("img_name", models.CharField(max_length=255, null=True)),
                ("price", models.IntegerField()),
                ("energy", models.FloatField()),
                ("protein", models.FloatField()),
                ("fat", models.FloatField()),
                ("carbohydrate", models.FloatField()),
                ("fiber", models.FloatField()),
                ("calcium", models.FloatField()),
                ("veggies", models.FloatField()),
            ],
        ),
    ]
