# Generated by Django 4.2.19 on 2025-02-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafeteria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="showmeal",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
