# Generated by Django 4.2.19 on 2025-03-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cafeteria", "0002_menu_showmeal"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="ja_meal_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
